{
  "containers": {
    "adp": [
      {
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-04T02:06:42.375Z"
        },
        "title": "CVE Program Container",
        "references": [
          {
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ],
            "url": "https://github.com/geopython/pywps/pull/616"
          },
          {
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ],
            "url": "https://github.com/geopython/OWSLib/issues/790"
          },
          {
            "name": "[debian-lts-announce] 20210904 [SECURITY] [DLA 2754-1] pywps security update",
            "tags": [
              "mailing-list",
              "x_refsource_MLIST",
              "x_transferred"
            ],
            "url": "https://lists.debian.org/debian-lts-announce/2021/09/msg00001.html"
          }
        ]
      }
    ]
  },
  "cveMetadata": {
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "assignerShortName": "mitre",
    "cveId": "CVE-2021-39371",
    "datePublished": "2021-08-23T00:03:20",
    "dateReserved": "2021-08-22T00:00:00",
    "dateUpdated": "2024-08-04T02:06:42.375Z",
    "state": "PUBLISHED"
  },
  "search": "解析验收测试文案"
}